spring.application.name=jira
spring.mongodb.uri=mongodb+srv://vaishnavikadam9325_db_user:F2aLolYEVK9amwYx@cluster0.blz1ogr.mongodb.net/jira?appName=Cluster0
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaishnavikadam9325@gmail.com
spring.mail.password=yzxnuajhahmeqwnd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=${FRONTEND_URL:http://localhost:3000}
server.port=${PORT:8080}